#!/bin/bash
# This deploy hook gets executed after dependencies are resolved and the
# build hook has been run but before the application has been started back
# up again.  This script gets executed directly, so it could be python, php,
# ruby, etc.

echo "------ Entering DEPLOY"
source $OPENSHIFT_HOMEDIR/python/virtenv/venv/bin/activate
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/opt/rh/postgresql92/root/usr/lib64/
echo "LD_LIBRARY_PATH = $LD_LIBRARY_PATH in deploy hook"

echo "Executing 'python $OPENSHIFT_REPO_DIR/$DJANGO_PROJECT_NAME/manage.py syncdb --noinput'"
python "$OPENSHIFT_REPO_DIR""$DJANGO_PROJECT_NAME"/manage.py syncdb --noinput
echo "Executing '$OPENSHIFT_REPO_DIR.openshift/action_hooks/secure_pgdb.py | tee ${OPENSHIFT_DATA_DIR}/CREDENTIALS'"
python "$OPENSHIFT_REPO_DIR".openshift/action_hooks/secure_pgdb.py | tee ${OPENSHIFT_DATA_DIR}/CREDENTIALS


echo "Executing 'python $OPENSHIFT_REPO_DIR/$DJANGO_PROJECT_NAME/manage.py collectstatic --noinput'"
python "$OPENSHIFT_REPO_DIR$DJANGO_PROJECT_NAME"/manage.py collectstatic --noinput
