#!/bin/bash
# workaround for https://bugzilla.redhat.com/show_bug.cgi?id=986219

echo "------ PRE-START-PYTHON"

LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/opt/rh/postgresql92/root/usr/lib64/
export LD_LIBRARY_PATH
echo "LD_LIBRARY_PATH = $LD_LIBRARY_PATH"